### ISSUE TITLE
Simplex

### ISSUE THREAD

**Issue by FedeNQ** [matramos/elrejunte#20]
**Tu pedido esta relacionado a algun algoritmo ya escrito en el notebook?**
- [ ] Si
- [x] No

**En que sección del notebook sugieres agregar o en cual ya se encuentra el algoritmo a mejorar??**

https://github.com/matramos/elrejunte/tree/master/notebook/secciones/math

**Describe con precisión que es lo que sugieres agregar**
Aprender y agregar Simplex

**Links o imágenes adicionales**
Agrega todo lo que te parezca que nos puede ayudar a agregar el algoritmo o mejora

**Comment by lsantire** [comment]
Listo: [e929cc3](https://github.com/matramos/elrejunte/commit/e929cc30e197d50f8010033d7ebf46082aab5ea8)
