### ISSUE TITLE
Revisar Biconexas, Puentes, Articulacion

### ISSUE THREAD

**Issue by FedeNQ** [matramos/elrejunte#21]
**Tu pedido esta relacionado a algun algoritmo ya escrito en el notebook?**
- [x] Si
- [ ] No

**En que sección del notebook sugieres agregar o en cual ya se encuentra el algoritmo a mejorar??**
https://github.com/matramos/elrejunte/blob/master/notebook/secciones/grafos/biconexas_puentes.cpp

**Describe con precisión que es lo que sugieres agregar**
Revisar Biconexas, Puentes, Articulacion

**Links o imágenes adicionales**
Agrega todo lo que te parezca que nos puede ayudar a agregar el algoritmo o mejora

**Comment by lsantire** [comment]
Listo: https://github.com/matramos/elrejunte/commit/2dedd752ee0c0a7ec4d887e16d9f108cedbafde4
